### ISSUE TITLE
Handling api requests

### ISSUE THREAD

**Issue by gabadi** [AlexGalays/fluxx#2]
How do you handle an api request in the actions?

**Comment by AlexGalays** [comment]
You handle any async aspect _outside_ stores/actions. Keeping the whole Action->dispatcher->Store pipeline synchronous is the only sane path for flux and happy debugging.

See this post on React's google groups, I think it answers your question nicely:  https://groups.google.com/forum/#!topic/reactjs/QQ-0dJ4eYUc

**Comment by gabadi** [comment]
Ok, i've seen before that thread before. But i've just understand it. Thank you
